package com.example.ui

val LANGUAGES_LIST = listOf(
    "en" to "🇬🇧 English",
    "hi" to "🇮🇳 हिंदी",
    "bn" to "🇧🇩 বাংলা",
    "ta" to "🇮🇳 தமிழ்",
    "te" to "🇮🇳 తెలుగు",
    "mr" to "🇮🇳 मराठी",
    "gu" to "🇮🇳 ગુજરાતી",
    "kn" to "🇮🇳 ಕನ್ನಡ",
    "ml" to "🇮🇳 മലയാളം",
    "pa" to "🇮🇳 ਪੰਜਾਬੀ",
    "ur" to "🇮🇳 اردو"
)

val I18N_LOCALIZED = mapOf(
    "en" to mapOf(
        "back" to "Back",
        "addItem" to "Add Item",
        "analytics" to "Analytics",
        "settings" to "Settings",
        "subtitle" to "Never waste food again",
        "addFood" to "+ Add Food",
        "home" to "Home",
        "searchItems" to "Search items...",
        "myInventory" to "My Inventory",
        "items" to "items",
        "totalItems" to "Total Items",
        "expiringSoon" to "Expiring Soon",
        "expired" to "Expired",
        "alerts" to "ALERTS",
        "more" to "more",
        "bulkDelete" to "Bulk Delete",
        "csv" to "Export CSV",
        "all" to "All",
        "fresh" to "Fresh",
        "expiring" to "Expiring",
        "noItems" to "No items found",
        "addFirst" to "Add your first food item!",
        "noExpired" to "No expired items",
        "itemRemoved" to "Item removed",
        "expiredCleared" to "Expired items cleared!",
        "csvExported" to "CSV exported!",
        "deleteExpiredQ" to "Delete all expired items?",
        "cancel" to "Cancel",
        "delete" to "Delete",
        "saveItem" to "Save Item",
        "photo" to "Photo",
        "choosePhoto" to "Choose Photo",
        "photoHint" to "Saved securely locally",
        "itemName" to "Item Name",
        "itemNamePh" to "e.g. Amul Milk, Apple...",
        "category" to "Category",
        "qtyUnit" to "Quantity & Unit",
        "qtyPh" to "e.g. 500",
        "price" to "Price — Optional",
        "purchaseDate" to "Purchase Date",
        "expiryDate" to "Expiry Date",
        "notes" to "Notes",
        "notesPh" to "e.g. Kept in back of fridge...",
        "nameRequired" to "Item name is required",
        "expiryRequired" to "Expiry date is required",
        "appearance" to "Appearance",
        "theme" to "Theme",
        "darkMode" to "Dark Mode",
        "lightMode" to "Light Mode",
        "language" to "Language",
        "notifications" to "Notifications",
        "enableNotifications" to "Enable Notifications",
        "dailyAt" to "Daily at 10:00 AM",
        "alertTune" to "Alert Tune",
        "storageInfo" to "Storage Info",
        "storage1" to "Items auto-saved to SQLite Room (offline)",
        "storage2" to "Settings persist across sessions",
        "storage3" to "Photos stored securely in app files",
        "storage4" to "100% offline — no internet needed",
        "statusFresh" to "FRESH",
        "statusSoon" to "EXPIRING SOON",
        "statusToday" to "EXPIRES TODAY",
        "statusExpired" to "EXPIRED",
        "expiresToday" to "Expires TODAY!",
        "wasted" to "Wasted",
        "itemsExpired" to "Items Expired",
        "thisMonth" to "This Month",
        "monthlyWaste" to "Monthly Waste",
        "wasteByCategory" to "Waste by Category",
        "expiredItems" to "Expired Items",
        "googleDriveBackup" to "Google Drive Backup",
        "backupNow" to "Backup to Drive",
        "restoreNow" to "Restore from Drive",
        "driveBackupDesc" to "Back up your data to a secure backup file in your Google Drive",
        "driveStatusNotConnected" to "Google Account not backup linked",
        "driveStatusBackupSuccess" to "Last backed up: Just now",
        "shareBackup" to "Share Local Backup File",
        "importBackup" to "Import Backup File",
        "dangerZone" to "Danger Zone",
        "clearAllData" to "Reset App Database",
        "clearDataConfirm" to "Are you absolutely sure you want to reset and clear all items?",
        "resetSuccess" to "App reset complete!",
        "csvReportTitle" to "Category-wise Expense Summary",
        "shopping" to "Shopping List"
    ),
    "hi" to mapOf(
        "shopping" to "खरीदारी",
        "back" to "वापस",
        "addItem" to "आइटम जोड़ें",
        "analytics" to "एनालिटिक्स",
        "settings" to "सेटिंग्स",
        "subtitle" to "खाना बर्बाद होने से बचाएँ",
        "addFood" to "+ खाना जोड़ें",
        "home" to "होम",
        "searchItems" to "आइटम खोजें...",
        "myInventory" to "मेरी इन्वेंटरी",
        "items" to "आइटम",
        "totalItems" to "कुल आइटम",
        "expiringSoon" to "जल्द खराब",
        "expired" to "खराब हो चुके",
        "alerts" to "अलर्ट",
        "more" to "और",
        "bulkDelete" to "बल्क डिलीट",
        "csv" to "CSV एक्सपोर्ट",
        "all" to "सभी",
        "fresh" to "फ्रेश",
        "expiring" to "जल्द खराब",
        "noItems" to "कोई आइटम नहीं मिला",
        "addFirst" to "अपना पहला food item जोड़ें!",
        "noExpired" to "कोई expired item नहीं",
        "itemRemoved" to "आइटम हटा दिया गया",
        "expiredCleared" to "Expired items हटा दिए गए!",
        "csvExported" to "CSV export हो गया!",
        "deleteExpiredQ" to "सभी expired items delete करें?",
        "cancel" to "कैंसल",
        "delete" to "डिलीट",
        "saveItem" to "आइटम सेव करें",
        "photo" to "फोटो",
        "choosePhoto" to "फोटो चुनें",
        "photoHint" to "सुरक्षित रूप से सेव किया गया",
        "itemName" to "आइटम का नाम",
        "itemNamePh" to "जैसे Amul Milk, Apple...",
        "category" to "कैटेगरी",
        "qtyUnit" to "मात्रा और यूनिट",
        "qtyPh" to "जैसे 500",
        "price" to "कीमत — वैकल्पिक",
        "purchaseDate" to "खरीद तारीख",
        "expiryDate" to "एक्सपायरी तारीख",
        "notes" to "नोट्स",
        "notesPh" to "जैसे फ्रिज के पीछे रखा है...",
        "nameRequired" to "Item name जरूरी है",
        "expiryRequired" to "Expiry date जरूरी है",
        "appearance" to "लुक",
        "theme" to "थीम",
        "darkMode" to "डार्क मोड",
        "lightMode" to "लाइट मोड",
        "language" to "भाषा",
        "notifications" to "नोटिफिकेशन",
        "enableNotifications" to "नोटिफिकेशन चालू करें",
        "dailyAt" to "सवेरे 10:00 बजे",
        "alertTune" to "अलर्ट ट्यून",
        "storageInfo" to "स्टोरेज जानकारी",
        "storage1" to "Items SQLite Room में offline save होते हैं",
        "storage2" to "Settings sessions में बनी रहती हैं",
        "storage3" to "Photos डिवाइस में सुरक्षित सेव होती हैं",
        "storage4" to "100% offline — internet की जरूरत नहीं",
        "statusFresh" to "फ्रेश",
        "statusSoon" to "जल्द खराब",
        "statusToday" to "आज खराब होगा",
        "statusExpired" to "खराब हो चुका",
        "expiresToday" to "आज expire होगा!",
        "wasted" to "बर्बाद",
        "itemsExpired" to "Expired Items",
        "thisMonth" to "इस महीने",
        "monthlyWaste" to "Monthly Waste",
        "wasteByCategory" to "Category के हिसाब से waste",
        "expiredItems" to "Expired Items",
        "googleDriveBackup" to "गूगल ड्राइव बैकअप",
        "backupNow" to "ड्राइव पर बैकअप लें",
        "restoreNow" to "ड्राइव से रिस्टोर करें",
        "driveBackupDesc" to "अपना डेटा अपने स्वयं के Google ड्राइव में एक सुरक्षित बैकअप फ़ाइल में सहेजें",
        "driveStatusNotConnected" to "गूगल अकाउंट लिंक नहीं है",
        "driveStatusBackupSuccess" to "पिछला बैकअप: अभी लिया गया",
        "shareBackup" to "लोकल बैकअप फाइल साझा करें",
        "importBackup" to "बैकअप फाइल इम्पोर्ट करें",
        "dangerZone" to "खतरे का क्षेत्र",
        "clearAllData" to "डेटाबेस रीसेट करें",
        "clearDataConfirm" to "क्या आप वाकई सभी आइटम रीसेट और हटाना चाहते हैं?",
        "resetSuccess" to "ऐप रीसेट हो गया!",
        "csvReportTitle" to "श्रेणी-वार व्यय मूल्य सारांश"
    ),
    "bn" to mapOf(
        "back" to "ফিরে যান",
        "addItem" to "আইটেম যোগ করুন",
        "analytics" to "বিশ্লেষণ",
        "settings" to "সেটিংস",
        "subtitle" to "খাবার অপচয় বন্ধ করুন",
        "addFood" to "+ খাবার যোগ করুন",
        "home" to "হোম",
        "searchItems" to "আইটেম খুঁজুন...",
        "myInventory" to "আমার ইনভেন্টরি",
        "items" to "আইটেম",
        "totalItems" to "মোট আইটেম",
        "expiringSoon" to "দ্রুত মেয়াদ শেষ",
        "expired" to "মেয়াদোত্তীর্ণ",
        "alerts" to "সতর্কতা",
        "more" to "আরো",
        "bulkDelete" to "একত্রে মুছুন",
        "csv" to "CSV ফাইল রপ্তানি",
        "all" to "সব",
        "fresh" to "তাজা",
        "expiring" to "মেয়াদ শেষ হচ্ছে",
        "noItems" to "কোনো আইটেম মেলেনি",
        "addFirst" to "আপনার প্রথম খাবার আইটেম যোগ করুন!",
        "noExpired" to "কোনো মেয়াদোত্তীর্ণ খাবার নেই",
        "itemRemoved" to "আইটেম সরানো হয়েছে",
        "expiredCleared" to "মেয়াদোত্তীর্ণ আইটেম সাফ!",
        "csvExported" to "CSV রপ্তানি সম্পন্ন!",
        "deleteExpiredQ" to "সব মেয়াদোত্তীর্ণ আইটেম মুছবেন?",
        "cancel" to "বাতিল",
        "delete" to "মুছুন",
        "saveItem" to "আইটেম সংরক্ষণ করুন",
        "photo" to "ছবি",
        "choosePhoto" to "ছবি চয়ন করুন",
        "photoHint" to "স্থানীয়ভাবে নিরাপদে সংরক্ষিত",
        "itemName" to "আইটেমের নাম",
        "itemNamePh" to "যেমন Amul Milk, Apple...",
        "category" to "বিভাগ",
        "qtyUnit" to "পরিমাণ ও একক",
        "qtyPh" to "যেমন ৫০০",
        "price" to "মূল্য — ঐচ্ছিক",
        "purchaseDate" to "ক্রয়ের তারিখ",
        "expiryDate" to "মেয়াদের তারিখ",
        "notes" to "টিকা",
        "notesPh" to "যেমন ফ্রিজের পেছনে রাখা হয়েছে...",
        "nameRequired" to "আইটেমের নাম আবশ্যক",
        "expiryRequired" to "মেয়াদের তারিখ আবশ্যক",
        "appearance" to "চেহারা",
        "theme" to "থিম",
        "darkMode" to "ডার্ক মোড",
        "lightMode" to "লাইট মোড",
        "language" to "ভাষা",
        "notifications" to "বিজ্ঞপ্তি",
        "enableNotifications" to "বিজ্ঞপ্তি সক্রিয় করুন",
        "dailyAt" to "প্রতিদিন সকাল ১০ টায়",
        "alertTune" to "সতর্কতা সুর",
        "storageInfo" to "স্টোরেজ তথ্য",
        "storage1" to "আইটেমগুলি SQLite রুমে অফলাইনে সংরক্ষিত থাকে",
        "storage2" to "সেটিংস প্রতিটি সেশনে সংরক্ষিত থাকে",
        "storage3" to "ছবি অ্যাপের ফাইলে নিরাপদে সংরক্ষিত থাকে",
        "storage4" to "১০০% অফলাইন — ইন্টারনেটের প্রয়োজন নেই",
        "statusFresh" to "তাজা",
        "statusSoon" to "মেয়াদ শেষ হচ্ছে",
        "statusToday" to "আজই মেয়াদ শেষ",
        "statusExpired" to "মেয়াদউত্তীর্ণ",
        "expiresToday" to "আজই মেয়াদ শেষ!",
        "wasted" to "অপচয়",
        "itemsExpired" to "মেয়াদোত্তীর্ণ আইটেম",
        "thisMonth" to "এই মাসে",
        "monthlyWaste" to "মাসিক অপচয়",
        "wasteByCategory" to "শ্রেণিভিত্তিক অপচয়",
        "expiredItems" to "মেয়াদোত্তীর্ণ খাবার",
        "googleDriveBackup" to "গুগল ড্রাইভ ব্যাকআপ",
        "backupNow" to "ড্রাইভ ব্যাকআপ",
        "restoreNow" to "ড্রাইভ থেকে পুনরুদ্ধার",
        "driveBackupDesc" to "আপনার ব্যক্তিগত গুগল ড্রাইভে নিরাপদে ডেটা ব্যাকআপ করুন",
        "driveStatusNotConnected" to "গুগল অ্যাকাউন্ট সংযুক্ত নেই",
        "driveStatusBackupSuccess" to "সর্বশেষ ব্যাকআপ: এই মাত্র",
        "shareBackup" to "লোকাল ব্যাকআপ ফাইল শেয়ার করুন",
        "importBackup" to "ব্যাকআপ ফাইল ইম্পোর্ট করুন",
        "dangerZone" to "বিপজ্জনক অঞ্চল",
        "clearAllData" to "ডেটাবেস রিসেট করুন",
        "clearDataConfirm" to "আপনি কি নিশ্চিতভাবে সব খাবার আইটেম মুছে ডেটাবেস রিসেট করতে চান?",
        "resetSuccess" to "অ্যাপ সম্পূর্ণ রিসেট হয়েছে!",
        "csvReportTitle" to "বিভাগীয় ব্যয় সারাংশ"
    ),
    "ta" to mapOf(
        "back" to "பின்னால்",
        "addItem" to "பொருளைச் சேர்",
        "analytics" to "பகுப்பாய்வு",
        "settings" to "அமைப்புகள்",
        "subtitle" to "உணவு வீணாவதைத் தடுக்கவும்",
        "addFood" to "+ உணவைச் சேர்",
        "home" to "முகப்பு",
        "searchItems" to "பொருட்களைத் தேடு...",
        "myInventory" to "எனது சரக்கு",
        "items" to "பொருட்கள்",
        "totalItems" to "மொத்த பொருட்கள்",
        "expiringSoon" to "விரைவில் காலாவதி",
        "expired" to "காலாவதியானது",
        "alerts" to "எச்சரிக்கைகள்",
        "more" to "மேலும்",
        "bulkDelete" to "மொத்தமாக நீக்கு",
        "csv" to "CSV ஏற்றுமதி",
        "all" to "அனைத்தும்",
        "fresh" to "புதியது",
        "expiring" to "காலாவதியாகிறது",
        "noItems" to "பொருட்கள் எதுவும் இல்லை",
        "addFirst" to "முதல் உணவுப் பொருளைச் சேர்க்கவும்!",
        "noExpired" to "காலாவதியான பொருட்கள் இல்லை",
        "itemRemoved" to "பொருள் நீக்கப்பட்டது",
        "expiredCleared" to "காலாவதியானவை அழிக்கப்பட்டன!",
        "csvExported" to "CSV ஏற்றுமதி செய்யப்பட்டது!",
        "deleteExpiredQ" to "காலாவதியான அனைத்தையும் நீக்கவா?",
        "cancel" to "ரத்து செய்",
        "delete" to "நீக்கு",
        "saveItem" to "பொருளைச் சேமி",
        "photo" to "புகைப்படம்",
        "choosePhoto" to "புகைப்படம் எடு",
        "photoHint" to "உள்ளூரில் பாதுகாப்பாக சேமிக்கப்பட்டது",
        "itemName" to "பொருளின் பெயர்",
        "itemNamePh" to "எ.கா. Amul Milk, Apple...",
        "category" to "வகை",
        "qtyUnit" to "அளவு & அலகு",
        "qtyPh" to "எ.கா. 500",
        "price" to "விலை — விருப்பத்தேர்வு",
        "purchaseDate" to "வாங்கிய தேதி",
        "expiryDate" to "காலாவதி தேதி",
        "notes" to "குறிப்புகள்",
        "notesPh" to "எ.கா. குளிர்சாதனப் பெட்டியின் பின்னே...",
        "nameRequired" to "பொருளின் பெயர் தேவை",
        "expiryRequired" to "காலாவதி தேதி தேவை",
        "appearance" to "தோற்றம்",
        "theme" to "தீம்",
        "darkMode" to "இருண்ட முறை",
        "lightMode" to "ஒளி முறை",
        "language" to "மொழி",
        "notifications" to "அறிவிப்புகள்",
        "enableNotifications" to "அறிவிப்புகளை இயக்கு",
        "dailyAt" to "தினமும் காலை 10:00 மணிக்கு",
        "alertTune" to "எச்சரிக்கை ஒலி",
        "storageInfo" to "சேமிப்பக தகவல்",
        "storage1" to "பொருட்கள் SQLite ரூமில் ஆஃப்லைனில் சேமிக்கப்படும்",
        "storage2" to "அமைப்புகள் தொடர்ந்து இருக்கும்",
        "storage3" to "புகைப்படங்கள் சாதனத்தில் பாதுகாப்பாக சேமிக்கப்படும்",
        "storage4" to "100% ஆஃப்லைன் — இணையம் தேவையில்லை",
        "statusFresh" to "புதியது",
        "statusSoon" to "விரைவில் காலாவதி",
        "statusToday" to "இன்று காலாவதி",
        "statusExpired" to "காலாவதியானது",
        "expiresToday" to "இன்று காலாவதியாகிறது!",
        "wasted" to "வீணானது",
        "itemsExpired" to "காலாவதியான பொருட்கள்",
        "thisMonth" to "இந்த மாதம்",
        "monthlyWaste" to "மாதாந்திர இழப்பு",
        "wasteByCategory" to "வகை வாரியாக இழப்பு",
        "expiredItems" to "காலாவதியானவை",
        "googleDriveBackup" to "கூகுள் டிரைவ் பேக்கப்",
        "backupNow" to "டிரைவில் சேமி",
        "restoreNow" to "டிரைவிலிருந்து மீட்டெடு",
        "driveBackupDesc" to "உங்கள் தரவை உங்கள் சொந்த கூகுள் டிரைவில் பாதுகாப்பாக காப்புப்பிரதி எடுக்கவும்",
        "driveStatusNotConnected" to "கூகுள் கணக்கு இணைக்கப்படவில்லை",
        "driveStatusBackupSuccess" to "கடைசி காப்புப்பிரதி: இப்போதே",
        "shareBackup" to "உள்ளூர் காப்புப்பிரதியை பகிர்",
        "importBackup" to "கோப்பை இறக்குமதி செய்",
        "dangerZone" to "ஆபத்தான பகுதி",
        "clearAllData" to "தரவுத்தளத்தை மீட்டமை",
        "clearDataConfirm" to "அனைத்து பொருட்களையும் நீக்கி தரவுத்தளத்தை மீட்டமைக்க விரும்புகிறீர்களா?",
        "resetSuccess" to "செயலி மீட்டமைக்கப்பட்டது!",
        "csvReportTitle" to "வகை வாரியான செலவு சுருக்கம்"
    ),
    "te" to mapOf(
        "back" to "వెనుకకు",
        "addItem" to "వస్తువును జోడించు",
        "analytics" to "విశ్లేషణ",
        "settings" to "సెట్టింగ్స్",
        "subtitle" to "ఆహారాన్ని వృథా చేయకండి",
        "addFood" to "+ ఆహారాన్ని జోడించు",
        "home" to "హోమ్",
        "searchItems" to "వెతకండి...",
        "myInventory" to "నా ఇన్వెంటరీ",
        "items" to "వస్తువులు",
        "totalItems" to "మొత్తం వస్తువులు",
        "expiringSoon" to "త్వరలో ముగిసేవి",
        "expired" to "గడువు ముగిసినవి",
        "alerts" to "హెచ్చరికలు",
        "more" to "మరిన్ని",
        "bulkDelete" to "బల్క్ డిలీట్",
        "csv" to "CSV ఎగుమతి",
        "all" to "అన్నీ",
        "fresh" to "తాజా",
        "expiring" to "త్వరలో గడువు ముగిసేవి",
        "noItems" to "ఏ వస్తువులూ లేవు",
        "addFirst" to "మొదటి ఆహార వస్తువును చేర్చండి!",
        "noExpired" to "గడువు ముగిసిన వస్తువులు లేవు",
        "itemRemoved" to "వస్తువు తొలగించబడింది",
        "expiredCleared" to "గడువు ముగిసినవి తొలగించబడ్డాయి!",
        "csvExported" to "CSV ఎగుమతి విజయవంతం!",
        "deleteExpiredQ" to "గడువు ముగిసిన వస్తువులన్నీ డిలీట్ చేయాలా?",
        "cancel" to "రద్దు చేయి",
        "delete" to "డిలీట్",
        "saveItem" to "వస్తువును సేవ్ చేయి",
        "photo" to "ఫోటో",
        "choosePhoto" to "ఫోటో ఎంచుకోండి",
        "photoHint" to "స్థానికంగా భద్రపరచబడింది",
        "itemName" to "వస్తువు పేరు",
        "itemNamePh" to "ఉదా. Amul Milk, Apple...",
        "category" to "వర్గం",
        "qtyUnit" to "పరిమాణం & యూనిట్",
        "qtyPh" to "ఉదా. 500",
        "price" to "ధర — ఐచ్ఛికం",
        "purchaseDate" to "కొనుగోలు తేదీ",
        "expiryDate" to "గడువు తేదీ",
        "notes" to "గమనికలు",
        "notesPh" to "ఉదా. ఫ్రిజ్ వెనుక భాగంలో...",
        "nameRequired" to "వస్తువు పేరు తప్పనిసరి",
        "expiryRequired" to "గడువు తేదీ తప్పనిసరి",
        "appearance" to "రూపం",
        "theme" to "థీమ్",
        "darkMode" to "డార్క్ మోడ్",
        "lightMode" to "లైట్ మోడ్",
        "language" to "భాష",
        "notifications" to "నోటిఫికేషన్లు",
        "enableNotifications" to "నోటిఫికేషన్లు ఆన్ చేయి",
        "dailyAt" to "ప్రతిరోజూ ఉదయం 10:00 గంటలకు",
        "alertTune" to "హెచ్చరిక ట్యూన్",
        "storageInfo" to "స్టోరేజ్ సమాచారం",
        "storage1" to "వస్తువులు SQLite రూమ్‌లో ఆఫ్‌లైన్‌గా సేవ్ చేయబడతాయి",
        "storage2" to "సెట్టింగ్‌లు అలాగే ఉంటాయి",
        "storage3" to "ఫోటోలు సురక్షితంగా యాప్ ఫైల్స్‌లో సేవ్ అవుతాయి",
        "storage4" to "100% ఆఫ్‌లైన్ — ఇంటర్నెట్ అవసరం లేదు",
        "statusFresh" to "తాజా",
        "statusSoon" to "త్వరలో గడువు ముగిసేవి",
        "statusToday" to "ఈరోజే ఆఖరి గడువు",
        "statusExpired" to "గడువు ముగిసినది",
        "expiresToday" to "ఈరోజే గడువు ముగుస్తుంది!",
        "wasted" to "వృథా అయినది",
        "itemsExpired" to "గడువు ముగిసిన వస్తువులు",
        "thisMonth" to "ఈ నెల",
        "monthlyWaste" to "నెలవారీ నష్టం",
        "wasteByCategory" to "వర్గాల వారీగా వృథా",
        "expiredItems" to "గడువు ముగిసినవి",
        "googleDriveBackup" to "గూగుల్ డ్రైవ్ బ్యాకప్",
        "backupNow" to "డ్రైవ్‌కు బ్యాకప్ చేయి",
        "restoreNow" to "డ్రైవ్ నుండి రీస్టోర్ చేయి",
        "driveBackupDesc" to "మీ వ్యక్తిగత గూగుల్ డ్రైవ్‌లో డేటాను సురక్షితంగా బ్యాకప్ చేయండి",
        "driveStatusNotConnected" to "గూగుల్ ఖాతా అనుసంధానించబడలేదు",
        "driveStatusBackupSuccess" to "చివరి బ్యాకప్: ఇప్పుడే",
        "shareBackup" to "స్థానిక బ్యాకప్ ఫైలును భాగస్వామ్యం చేయి",
        "importBackup" to "బ్యాకప్ ఫైల్‌ను ఇంపోర్ట్ చేయి",
        "dangerZone" to "ప్రమాదకర ప్రాంతం",
        "clearAllData" to "డేటాబేస్ రీసెట్ చేయి",
        "clearDataConfirm" to "ఖచ్చితంగా అన్ని వస్తువులను తొలగించి రీసెట్ చేయాలనుకుంటున్నారా?",
        "resetSuccess" to "యాప్ విజయవంతంగా రీసెట్ చేయబడింది!",
        "csvReportTitle" to "వర్గాల వారీ ఖర్చుల నివేదిక"
    ),
    "mr" to mapOf(
        "back" to "मागे",
        "addItem" to "नवीन जोडा",
        "analytics" to "विश्लेषण",
        "settings" to "सेटिंग्ज",
        "subtitle" to "अन्नाची नासाडी टाळा",
        "addFood" to "+ अन्न जोडा",
        "home" to "होम",
        "searchItems" to "शोध घ्या...",
        "myInventory" to "माझी इन्व्हेंटरी",
        "items" to "वस्तु",
        "totalItems" to "एकूण वस्तू",
        "expiringSoon" to "लवकरच खराब होणारे",
        "expired" to "खराब झालेले",
        "alerts" to "अलर्ट",
        "more" to "अधिक",
        "bulkDelete" to "एकत्रित डिलीट",
        "csv" to "CSV एक्सपोर्ट",
        "all" to "सर्व",
        "fresh" to "ताजे",
        "expiring" to "लवकर संपणारे",
        "noItems" to "काही आढळले नाही",
        "addFirst" to "पहिली वस्तू जोडा!",
        "noExpired" to "खराब झालेले पदार्थ नाहीत",
        "itemRemoved" to "वस्तू काढली गेली",
        "expiredCleared" to "एक्सपायर्ड वस्तू हटवल्या!",
        "csvExported" to "CSV एक्सपोर्ट यशस्वी!",
        "deleteExpiredQ" to "सर्व एक्सपायर्ड वस्तू हटवायच्या?",
        "cancel" to "रद्द करा",
        "delete" to "हटवा",
        "saveItem" to "वस्तू जतन करा",
        "photo" to "फोटो",
        "choosePhoto" to "फोटो निवडा",
        "photoHint" to "स्थानिक पातळीवर सुरक्षित जतन",
        "itemName" to "वस्तूचे नाव",
        "itemNamePh" to "उदा. Amul Milk, Apple...",
        "category" to "वर्ग",
        "qtyUnit" to "प्रमाण आणि युनिट",
        "qtyPh" to "उदा. ५००",
        "price" to "किंमत — ऐच्छिक",
        "purchaseDate" to "खरेदी तारीख",
        "expiryDate" to "एक्सपायरी तारीख",
        "notes" to "नोंदी",
        "notesPh" to "उदा. फ्रीजच्या मागे ठेवले आहे...",
        "nameRequired" to "वस्तूचे नाव आवश्यक आहे",
        "expiryRequired" to "एक्सपायरी तारीख आवश्यक आहे",
        "appearance" to "देखावा",
        "theme" to "थीम",
        "darkMode" to "डार्क मोड",
        "lightMode" to "लाईट मोड",
        "language" to "भाषा",
        "notifications" to "सूचना",
        "enableNotifications" to "सूचना सुरू करा",
        "dailyAt" to "रोज सकाळी १०:०० वाजता",
        "alertTune" to "अलर्ट ट्यून",
        "storageInfo" to "स्टोरेज माहिती",
        "storage1" to "डेटा ऑफलाइन SQLite रूम मध्ये जतन होतो",
        "storage2" to "सेटिंग्ज सेव्ह राहतात",
        "storage3" to "फोटो उपकरणात सुरक्षित सेव्ह होतात",
        "storage4" to "१००% ऑफलाइन — इंटरनेटची गरज नाही",
        "statusFresh" to "ताजे",
        "statusSoon" to "लवकरच खराब",
        "statusToday" to "आज एक्सपायरी आहे",
        "statusExpired" to "खराब झाले",
        "expiresToday" to "आजच खराब होईल!",
        "wasted" to "वाया गेले",
        "itemsExpired" to "खराब झालेले पदार्थ",
        "thisMonth" to "या महिन्यात",
        "monthlyWaste" to "मासिक नासाडी",
        "wasteByCategory" to "वर्गावर नासाडी",
        "expiredItems" to "खराब झालेल्या वस्तू",
        "googleDriveBackup" to "गुगल ड्राइव्ह बॅकअप",
        "backupNow" to "ड्राइव्हवर जतन करा",
        "restoreNow" to "ड्राइव्हवरून पुनर्प्राप्त करा",
        "driveBackupDesc" to "तुमचा डेटा गुगल ड्राइव्हवर सुरक्षितपणे बॅकअप करा",
        "driveStatusNotConnected" to "गुगल खाते जोडलेले नाही",
        "driveStatusBackupSuccess" to "शेवटचा बॅकअप: आत्ताच",
        "shareBackup" to "बॅकअप फाईल शेअर करा",
        "importBackup" to "बॅकअप फाईल इम्पोर्ट करा",
        "dangerZone" to "धोकादायक क्षेत्र",
        "clearAllData" to "डेटाबेस रिसेट करा",
        "clearDataConfirm" to "तुम्ही नक्की सर्व वस्तू काढून रिसेट करू इच्छिता?",
        "resetSuccess" to "अॅप रीसेट झाले!",
        "csvReportTitle" to "वर्गानुसार खर्चाचा सारांश"
    ),
    "gu" to mapOf(
        "back" to "પાછા",
        "addItem" to "વસ્તુ ઉમેરો",
        "analytics" to "એનાલિટિક્સ",
        "settings" to "સેટિંગ્સ",
        "subtitle" to "ખોરાકનો બગાડ અટકાવો",
        "addFood" to "+ ખોરાક ઉમેરો",
        "home" to "હોમ",
        "searchItems" to "શોધો...",
        "myInventory" to "મારી યાદી",
        "items" to "વસ્તુઓ",
        "totalItems" to "કુલ વસ્તુઓ",
        "expiringSoon" to "ટૂંક સમયમાં બગડશે",
        "expired" to "મુદત વીતી ગયેલ",
        "alerts" to "ચેતવણીઓ",
        "more" to "વધુ",
        "bulkDelete" to "બલ્ક ડિલીટ",
        "csv" to "CSV નિકાસ",
        "all" to "બધા",
        "fresh" to "તાજું",
        "expiring" to "ટૂંક સમયમાં મુદત વીતશે",
        "noItems" to "કોઈ વસ્તુ મળી નથી",
        "addFirst" to "તમારી પ્રથમ વસ્તુ ઉમેરો!",
        "noExpired" to "કોઈ બગડેલી વસ્તુ નથી",
        "itemRemoved" to "વસ્તુ હટાવી દીધી",
        "expiredCleared" to "મુદત વીતી ગયેલ સાફ!",
        "csvExported" to "CSV નિકાસ સફળ!",
        "deleteExpiredQ" to "બધી બગડેલી વસ્તુ કાઢી નાખવી?",
        "cancel" to "રદ કરો",
        "delete" to "કાઢી નાખો",
        "saveItem" to "વસ્તુ સેવ કરો",
        "photo" to "ફોટો",
        "choosePhoto" to "ફોટો પસંદ કરો",
        "photoHint" to "લોકલ ઉપકરણમાં સુરક્ષિત સેવ",
        "itemName" to "વસ્તુ નામ",
        "itemNamePh" to "જેમ કે Amul Milk, Apple...",
        "category" to "કેટેગરી",
        "qtyUnit" to "માત્રા અને યુનિટ",
        "qtyPh" to "જેમ કે 500",
        "price" to "કિંમત — વૈકલ્પિક",
        "purchaseDate" to "ખરીદી તારીખ",
        "expiryDate" to "એક્સપાયરી તારીખ",
        "notes" to "નોંધો",
        "notesPh" to "જેમ કે ફ્રીજની પાછળ રાખેલ છે...",
        "nameRequired" to "વસ્તુનું નામ જરૂરી છે",
        "expiryRequired" to "એક્સપાયરી તારીખ જરૂરી છે",
        "appearance" to "દેખાવ",
        "theme" to "થીમ",
        "darkMode" to "ડાર્ક મોડ",
        "lightMode" to "લાઇટ મોડ",
        "language" to "ભાષા",
        "notifications" to "નોટિફિકેશન",
        "enableNotifications" to "નોટિફિકેશન ચાલુ કરો",
        "dailyAt" to "દરરોજ સવારે ૧૦:૦૦ વાગ્યે",
        "alertTune" to "અલર્ટ ટ્યુન",
        "storageInfo" to "સ્ટોરેજ માહિતી",
        "storage1" to "વસ્તુઓ SQLite રૂમમાં ઓફલાઇન સેવ થાય છે",
        "storage2" to "સેટિંગ્સ સેવ રહે છે",
        "storage3" to "ફોટા ઉપકરણમાં સુરક્ષિત સેવ થાય છે",
        "storage4" to "૧૦૦% ઓફલાઇન — ઇન્ટરનેટ વગર ચાલશે",
        "statusFresh" to "તાજું",
        "statusSoon" to "ટૂંક સમયમાં બગડશે",
        "statusToday" to "આજ રોજ મુદત વીતશે",
        "statusExpired" to "મુદત વીતી ગયેલ",
        "expiresToday" to "આજે જ મુદત પૂર્ણ થશે!",
        "wasted" to "બગડેલ કિંમત",
        "itemsExpired" to "બગડેલી વસ્તુઓ",
        "thisMonth" to "આ મહિને",
        "monthlyWaste" to "માસિક નુકસાન",
        "wasteByCategory" to "કેટેગરી મુજબ નુકસાન",
        "expiredItems" to "એક્સપાયર થયેલ વસ્તુ",
        "googleDriveBackup" to "ગુગલ ડ્રાઇવ બેકઅપ",
        "backupNow" to "ડ્રાઇવ પર સેવ કરો",
        "restoreNow" to "ડ્રાઇવમાંથી પાછું મેળવો",
        "driveBackupDesc" to "તમારો ડેટા ગુગલ ડ્રાઇવમાં સુરક્ષિત રીતે સેવ કરો",
        "driveStatusNotConnected" to "ગુગલ એકાઉન્ટ લિંક નથી",
        "driveStatusBackupSuccess" to "છેલ્લું બેકઅપ: અત્યારે જ",
        "shareBackup" to "બેકઅપ ફાઈલ શેર કરો",
        "importBackup" to "બેકઅપ ફાઈલ ઇમ્પોર્ટ કરો",
        "dangerZone" to "જોખમી વિસ્તાર",
        "clearAllData" to "ડેટાબેઝ રીસેટ કરો",
        "clearDataConfirm" to "શું તમે ખરેખર બધો ડેટા કાઢી નાખવા માંગો છો?",
        "resetSuccess" to "એપ સંપૂર્ણ રીસેટ થયેલ છે!",
        "csvReportTitle" to "કેટેગરી મુજબ ખર્ચ પત્રક"
    ),
    "kn" to mapOf(
        "back" to "ಹಿಂದಕ್ಕೆ",
        "addItem" to "ವಸ್ತು ಸೇರಿಸಿ",
        "analytics" to "ವಿಶ್ಲೇಷಣೆ",
        "settings" to "ಸೆಟ್ಟಿಂಗ್ಸ್",
        "subtitle" to "ಆಹಾರ ವ್ಯರ್ಥವಾಗುವುದನ್ನು ತಡೆಯಿರಿ",
        "addFood" to "+ ಆಹಾರ ಸೇರಿಸಿ",
        "home" to "ಹೋಮ್",
        "searchItems" to "ಹುಡುಕಿ...",
        "myInventory" to "ನನ್ನ ಇನ್ವೆಂಟರಿ",
        "items" to "ವಸ್ತುಗಳು",
        "totalItems" to "ಒಟ್ಟು ವಸ್ತುಗಳು",
        "expiringSoon" to "ಶೀಘ್ರದಲ್ಲೇ ಮುಗಿಯುವ",
        "expired" to "ಅವಧಿ ಮುಗಿದ",
        "alerts" to "ಎಚ್ಚರಿಕೆಗಳು",
        "more" to "ಇನ್ನಷ್ಟು",
        "bulkDelete" to "ಬಲ್ಕ್ ಡಿಲೀಟ್",
        "csv" to "CSV ರಫ್ತು",
        "all" to "ಎಲ್ಲಾ",
        "fresh" to "ತಾಜಾ",
        "expiring" to "ಅವಧಿ ಮುಗಿಯುತ್ತಿರುವ",
        "noItems" to "ಯಾವುದೇ ವಸ್ತು ಕಂಡುಬಂದಿಲ್ಲ",
        "addFirst" to "ನಿಮ್ಮ ಮೊದಲ ಆಹಾರ ವಸ್ತುವನ್ನು ಸೇರಿಸಿ!",
        "noExpired" to "ಯಾವುದೇ ಅವಧಿ ಮುಗಿದ ವಸ್ತುಗಳಿಲ್ಲ",
        "itemRemoved" to "ವಸ್ತು ತೆಗೆದುಹಾಕಲಾಗಿದೆ",
        "expiredCleared" to "ಅವಧಿ ಮುಗಿದ ವಸ್ತುಗಳನ್ನು ತೆರವುಗೊಳಿಸಲಾಗಿದೆ!",
        "csvExported" to "CSV ಯಶಸ್ವಿಯಾಗಿ ರಫ್ತಾಗಿದೆ!",
        "deleteExpiredQ" to "ಅವಧಿ ಮುಗಿದ ಎಲ್ಲಾ ವಸ್ತುಗಳನ್ನು ತೆಗೆದುಹಾಕಬೇಕೆ?",
        "cancel" to "ರದ್ದುಮಾಡಿ",
        "delete" to "ತೆಗೆದುಹಾಕಿ",
        "saveItem" to "ವಸ್ತು ಉಳಿಸಿ",
        "photo" to "ಭಾವಚಿತ್ರ",
        "choosePhoto" to "ಫೋಟೋ ಆಯ್ಕೆಮಾಡಿ",
        "photoHint" to "ಸ್ಥಳೀಯವಾಗಿ ಸುರಕ್ಷಿತವಾಗಿ ಸಂಗ್ರಹಿಸಲಾಗಿದೆ",
        "itemName" to "ಸಾಮಗ್ರಿಯ ಹೆಸರು",
        "itemNamePh" to "ಉದಾ. Amul Milk, Apple...",
        "category" to "ವರ್ಗ",
        "qtyUnit" to "ಪ್ರಮಾಣ ಮತ್ತು ಯುನಿಟ್",
        "qtyPh" to "ಉದಾ. 500",
        "price" to "ಬೆಲೆ — ಐಚ್ಛಿಕ",
        "purchaseDate" to "ಖರೀದಿಸಿದ ದಿನಾಂಕ",
        "expiryDate" to "ಅವಧಿ ಮುಗಿಯುವ ದಿನಾಂಕ",
        "notes" to "ಟಿಪ್ಪಣಿಗಳು",
        "notesPh" to "ಉದಾ. ಫ್ರಿಜ್ ಹಿಂಭಾಗದಲ್ಲಿ ಇರಿಸಲಾಗಿದೆ...",
        "nameRequired" to "ಸಾಮಗ್ರಿಯ ಹೆಸರು ಕಡ್ಡಾಯ",
        "expiryRequired" to "ಅವಧಿ ಮುಗಿಯುವ ದಿನಾಂಕ ಕಡ್ಡಾಯ",
        "appearance" to "ಗೋಚರತೆ",
        "theme" to "ಥೀಮ್",
        "darkMode" to "ಡಾರ್ಕ್ ಮೋಡ್",
        "lightMode" to "ಲೈಟ್ ಮೋಡ್",
        "language" to "ಭಾಷೆ",
        "notifications" to "ಅಧಿಸೂಚನೆಗಳು",
        "enableNotifications" to "ಅಧಿಸೂಚನೆಗಳನ್ನು ಸಕ್ರಿಯಗೊಳಿಸಿ",
        "dailyAt" to "ದಿನನಿತ್ಯ ಬೆಳಿಗ್ಗೆ 10:00 ಕ್ಕೆ",
        "alertTune" to "ಎಚ್ಚರಿಕೆಯ ರಾಗ",
        "storageInfo" to "ಸ್ಟೋರೇಜ್ ಮಾಹಿತಿ",
        "storage1" to " SQLite ರೂಮ್‌ನಲ್ಲಿ ಆಫ್‌ಲೈನ್‌ನಲ್ಲಿ ಸಂಗ್ರಹಿಸಲಾಗುತ್ತದೆ",
        "storage2" to "ಸೆಟ್ಟಿಂಗ್ಸ್ ಉಳಿಯುತ್ತದೆ",
        "storage3" to "ಫೋಟೋಗಳು ಸುರಕ್ಷಿತವಾಗಿ ಮೊಬೈಲ್‌ನಲ್ಲಿ ಇರುತ್ತವೆ",
        "storage4" to "100% ಆಫ್‌ಲೈನ್ — ಇಂಟರ್ನೆಟ್ ಅಗತ್ಯವಿಲ್ಲ",
        "statusFresh" to "ತಾಜಾ",
        "statusSoon" to "ಶೀಘ್ರದಲ್ಲೇ ಮುಗಿಯುವ",
        "statusToday" to "ಇಂದೇ ಅವಧಿ ಮುಗಿಯುತ್ತದೆ",
        "statusExpired" to "ಅವಧಿ ಮುಗಿದಿದೆ",
        "expiresToday" to "ಇಂದೇ ಅವಧಿ ಮುಗಿಯುತ್ತದೆ!",
        "wasted" to "ವ್ಯರ್ಥವಾದ ಬೆಲೆ",
        "itemsExpired" to "ಅವಧಿ ಮುಗಿದ ವಸ್ತುಗಳು",
        "thisMonth" to "ಈ ತಿಂಗಳು",
        "monthlyWaste" to "ಮಾಸಿಕ ವ್ಯರ್ಥ",
        "wasteByCategory" to "ವರ್ಗಾವಾರು ವ್ಯರ್ಥ",
        "expiredItems" to "ಅವಧಿ ಮುಗಿದ ಸಾಮಗ್ರಿ",
        "googleDriveBackup" to "ಗೂಗಲ್ ಡ್ರೈವ್ ಬ್ಯಾಕಪ್",
        "backupNow" to "ಡ್ರೈವ್ ಬ್ಯಕಪ್ ಮಾಡಿಕೊಳ್ಳಿ",
        "restoreNow" to "ಡ್ರೈವ್‌ನಿಂದ ಮರುಪಡೆಯಿರಿ",
        "driveBackupDesc" to "ನಿಮ್ಮ ಗೂಗಲ್ ಡ್ರೈವ್‌ನಲ್ಲಿ ಡೇಟಾವನ್ನು ಸುರಕ್ಷಿತವಾಗಿ ಬ್ಯಾಕಪ್ ಮಾಡಿ",
        "driveStatusNotConnected" to "ಗೂಗಲ್ ಖಾತೆ ಲಿಂಕ್ ಆಗಿಲ್ಲ",
        "driveStatusBackupSuccess" to "ಕೊನೆಯ ಬ್ಯಾಕಪ್: ಇತ್ತೀಚೆಗೆ",
        "shareBackup" to "ಲೋಕಲ್ ಬ್ಯಾಕಪ್ ಫೈಲ್ ಹಂಚಿಕೊಳ್ಳಿ",
        "importBackup" to "ಬ್ಯಾಕಪ್ ಫೈಲ್ ಇಂಪೋರ್ಟ್ ಮಾಡಿ",
        "dangerZone" to "ಅಪಾಯದ ವಲಯ",
        "clearAllData" to "ಡೇಟಾಬೇಸ್ ಮರುಹೊಂದಿಸಿ",
        "clearDataConfirm" to "ಖಂಡಿತವಾಗಿಯೂ ಎಲ್ಲಾ ವಸ್ತುಗಳನ್ನು ಅಳಿಸಿ ಮರುಹೊಂದಿಸಬೇಕೆ?",
        "resetSuccess" to "ಅಪ್ಲಿಕೇಶನ್ ರಿಸೆಟ್ ಯಶಸ್ವಿಯಾಗಿದೆ!",
        "csvReportTitle" to "ವರ್ಗಾವಾರು ಖರ್ಚುಗಳ ಸಾರಾಂಶ"
    ),
    "ml" to mapOf(
        "back" to "പിന്നിലേക്ക്",
        "addItem" to "ഇനം ചേർക്കുക",
        "analytics" to "വിശകലനം",
        "settings" to "ക്രമീകരണങ്ങൾ",
        "subtitle" to "ഭക്ഷണം പാഴാക്കുന്നത് ഒഴിവാക്കൂ",
        "addFood" to "+ ഭക്ഷണം ചേർക്കുക",
        "home" to "ഹോം",
        "searchItems" to "തിരയുക...",
        "myInventory" to "എന്റെ ലിസ്റ്റ്",
        "items" to "ഇനങ്ങൾ",
        "totalItems" to "ആകെ ഇനങ്ങൾ",
        "expiringSoon" to "ഉടൻ കാലാവധി തീരുന്നവ",
        "expired" to "കാലാവധി കഴിഞ്ഞവ",
        "alerts" to "അലർട്ടുകൾ",
        "more" to "കൂടുതൽ",
        "bulkDelete" to "മൊത്തമായി ഇല്ലാതാക്കുക",
        "csv" to "CSV എക്സ്പോർട്ട്",
        "all" to "എല്ലാം",
        "fresh" to "ഫ്രഷ്",
        "expiring" to "കാലാവധി തീരാറായവ",
        "noItems" to "ഇനങ്ങൾ ഒന്നും കണ്ടെത്തിയില്ല",
        "addFirst" to "ആദ്യത്തെ ഭക്ഷണം ചേർക്കൂ!",
        "noExpired" to "കാലാവധി കഴിഞ്ഞ ഇനങ്ങൾ ഇല്ല",
        "itemRemoved" to "നീക്കം ചെയ്തു",
        "expiredCleared" to "കാലാവധി കഴിഞ്ഞവ നീക്കം ചെയ്തു!",
        "csvExported" to "CSV വിജയകരമായി സേവ് ചെയ്തു!",
        "deleteExpiredQ" to "കാലാവധി കഴിഞ്ഞ എല്ലാ ഇനങ്ങളും ഇല്ലാതാക്കണോ?",
        "cancel" to "റദ്ദാക്കുക",
        "delete" to "ഇല്ലാതാക്കുക",
        "saveItem" to "സേവ് ചെയ്യുക",
        "photo" to "ഫോട്ടോ",
        "choosePhoto" to "ഫോട്ടോ തിരഞ്ഞെടുക്കുക",
        "photoHint" to "ഫോണിൽ സുരക്ഷിതമായി സൂക്ഷിച്ചിരിക്കുന്നു",
        "itemName" to "സാധനത്തിന്റെ പേര്",
        "itemNamePh" to "ഉദാ. Amul Milk, Apple...",
        "category" to "വിഭാഗം",
        "qtyUnit" to "അളവും യൂണിറ്റും",
        "qtyPh" to "ഉദാ. 500",
        "price" to "വില — നിർബന്ധമില്ല",
        "purchaseDate" to "വാങ്ങിയ തീയതി",
        "expiryDate" to "കാലാവധി തീയതി",
        "notes" to "കുറിപ്പുകൾ",
        "notesPh" to "ഉദാ. ഫ്രിഡ്ജിന്റെ പുറകിലുണ്ട്...",
        "nameRequired" to "ഇനത്തിന്റെ പേര് നൽകണം",
        "expiryRequired" to "കാലാവധി തീയതി നൽകണം",
        "appearance" to "രൂപഭാവം",
        "theme" to "തീം",
        "darkMode" to "ഡാർക്ക് മോഡ്",
        "lightMode" to "ലൈറ്റ് മോഡ്",
        "language" to "ഭാഷ",
        "notifications" to "അറിയിപ്പുകൾ",
        "enableNotifications" to "അറിയിപ്പുകൾ ഓൺ ചെയ്യുക",
        "dailyAt" to "ദിവസവും രാവിലെ 10:00 ന്",
        "alertTune" to "അലർട്ട് ട്യൂൺ",
        "storageInfo" to "സംഭരണ വിവരങ്ങൾ",
        "storage1" to "SQLite റൂമിൽ ഓഫ്ലൈനായി സേവ് ചെയ്തിരിക്കുന്നു",
        "storage2" to "ക്രമീകരണങ്ങൾ ഫോണിൽ തുടരും",
        "storage3" to "ഫോട്ടോകൾ ഫോണിൽ സുരക്ഷിതമായിരിക്കും",
        "storage4" to "100% ഓഫ്ലൈൻ — ഇന്റർനെറ്റ് ആവശ്യമില്ല",
        "statusFresh" to "ഫ്രഷ്",
        "statusSoon" to "ഉടൻ കാലാവധി തീരും",
        "statusToday" to "ഇന്ന് കാലാവധി തീരും",
        "statusExpired" to "കാലാവധി കഴിഞ്ഞു",
        "expiresToday" to "ഇന്ന് കാലാവധി തീരും!",
        "wasted" to "പാഴായ തുക",
        "itemsExpired" to "കാലാവധി കഴിഞ്ഞ ഇനങ്ങൾ",
        "thisMonth" to "ഈ മാസം",
        "monthlyWaste" to "മാസത്തെ നഷ്ടം",
        "wasteByCategory" to "വിഭാഗം തിരിച്ച് നഷ്ടം",
        "expiredItems" to "കാലാവധി കഴിഞ്ഞവ",
        "googleDriveBackup" to "ഗൂഗിൾ ഡ്രൈവ് ബാക്കപ്പ്",
        "backupNow" to "ഡ്രൈവിലേക്ക് ബാക്കപ്പ് ചെയ്യുക",
        "restoreNow" to "ഡ്രൈവിൽ നിന്ന് വീണ്ടെടുക്കുക",
        "driveBackupDesc" to "നിങ്ങളുടെ ഗൂഗിൾ ഡ്രൈവിലേക്ക് ഡാറ്റ സുരക്ഷിതമായി മാറ്റുക",
        "driveStatusNotConnected" to "ഗൂഗിൾ അക്കൗണ്ട് ബന്ധിപ്പിച്ചിട്ടില്ല",
        "driveStatusBackupSuccess" to "അവസാന ബാക്കപ്പ്: ഇപ്പോൾ",
        "shareBackup" to "ബാക്കപ്പ് ഫയൽ പങ്കിടുക",
        "importBackup" to "ബാക്കപ്പ് ഫയൽ കൊണ്ടുവരിക",
        "dangerZone" to "അപകട മേഖല",
        "clearAllData" to "ഡാറ്റാബേസ് പൂർണ്ണമായി ഒഴിവാക്കുക",
        "clearDataConfirm" to "തീർച്ചയായും എല്ലാ ഇനങ്ങളും ഒഴിവാക്കണോ?",
        "resetSuccess" to "ആപ്പ് നിർജ്ജീവമാക്കി പുനഃക്രമീകരിച്ചു!",
        "csvReportTitle" to "ചെലവ് വിവരങ്ങൾവിഭാഗം തിരിച്ച്"
    ),
    "pa" to mapOf(
        "back" to "ਵਾਪਸ",
        "addItem" to "ਆਈਟਮ ਜੋੜੋ",
        "analytics" to "ਵਿਸ਼ਲੇਸ਼ਣ",
        "settings" to "ਸੈਟਿੰਗਜ਼",
        "subtitle" to "ਆਹਾਰ ਦੀ ਬਰਬਾਦੀ ਤੋਂ ਬਚੋ",
        "addFood" to "+ ਭੋਜਨ ਜੋੜੋ",
        "home" to "ਹੋਮ",
        "searchItems" to "ਆਈਟਮ ਲੱਭੋ...",
        "myInventory" to "ਮੇਰੀ ਸੂਚੀ",
        "items" to "ਆਈਟਮਾਂ",
        "totalItems" to "ਕੁੱਲ ਆਈਟਮਾਂ",
        "expiringSoon" to "ਜਲਦ ਖ਼ਰਾਬ",
        "expired" to "ਖ਼ਰਾਬ ਹੋ ਚੁੱਕੇ",
        "alerts" to "ਅਲਰਟ",
        "more" to "ਹੋਰ",
        "bulkDelete" to "ਇੱਕਠੇ ਡਿਲੀਟ",
        "csv" to "CSV ਐਕਸਪੋਰਟ",
        "all" to "ਸਭ",
        "fresh" to "ਤਾਜ਼ਾ",
        "expiring" to "ਖ਼ਰਾਬ ਹੋਣ ਵਾਲਾ",
        "noItems" to "ਕੋਈ ਆਈਟਮ ਨਹੀਂ ਮਿਲੀ",
        "addFirst" to "ਆਪਣੀ ਪਹਿਲੀ ਭੋਜਨ ਆਈਟਮ ਜੋੜੋ!",
        "noExpired" to "ਕੋਈ ਖ਼ਰਾਬ ਆਈਟਮ ਨਹੀਂ",
        "itemRemoved" to "ਆਈਟਮ ਹਟਾ ਦਿੱਤੀ ਗਈ",
        "expiredCleared" to "ਖ਼ਰਾਬ ਆਈਟਮਾਂ ਸਾਫ!",
        "csvExported" to "CSV ਐਕਸਪੋਰਟ ਹੋ ਗਿਆ!",
        "deleteExpiredQ" to "ਸਾਰੀਆਂ ਖ਼ਰਾਬ ਆਈਟਮਾਂ ਹਟਾਈਏ?",
        "cancel" to "ਰੱਦ ਕਰੋ",
        "delete" to "ਡਿਲੀਟ",
        "saveItem" to "ਆਈਟਮ ਸੇਵ ਕਰੋ",
        "photo" to "ਫੋਟੋ",
        "choosePhoto" to "ਫੋਟੋ ਚੁਣੋ",
        "photoHint" to "ਸੁਰੱਖਿਅਤ ਸੇਵ ਕੀਤਾ ਗਿਆ",
        "itemName" to "ਆਈਟਮ ਦਾ ਨਾਮ",
        "itemNamePh" to "ਜਿਵੇਂ Amul Milk, Apple...",
        "category" to "ਕੈਟੇਗਰੀ",
        "qtyUnit" to "ਮਾਤਰਾ ਅਤੇ ਯੂਨਿਟ",
        "qtyPh" to "ਜਿਵੇਂ 500",
        "price" to "ਕੀਮਤ — ਵੈਕਲਪਿਕ",
        "purchaseDate" to "ਖਰੀਦ ਦੀ ਤਾਰੀਖ",
        "expiryDate" to "ਮਿਆਦ ਪੁੱਗਣ ਤਾਰੀਖ",
        "notes" to "ਨੋਟਿਸ",
        "notesPh" to "ਜਿਵੇਂ ਫਰਿੱਜ ਦੇ ਪਿੱਛੇ ਰੱਖਿਆ ਹੈ...",
        "nameRequired" to "ਆਈਟਮ ਦਾ ਨਾਮ ਜ਼ਰੂਰੀ ਹੈ",
        "expiryRequired" to "ਮਿਆਦ ਪੁੱਗਣ ਦੀ ਤਾਰੀਖ ਜ਼ਰੂਰੀ ਹੈ",
        "appearance" to "ਦਿੱਖ",
        "theme" to "ਥੀਮ",
        "darkMode" to "ਡਾਰਕ ਮੋਡ",
        "lightMode" to "ਲਾਈਟ ਮੋਡ",
        "language" to "ਭਾਸ਼ਾ",
        "notifications" to "ਨੋਟੀਫਿਕੇਸ਼ਨ",
        "enableNotifications" to "ਨੋਟੀਫਿਕੇਸ਼ਨ ਚਾਲੂ ਕਰੋ",
        "dailyAt" to "ਹਰ ਰੋਜ਼ ਸਵੇਰੇ 10:00 ਵਜੇ",
        "alertTune" to "ਅਲਰਟ ਟਿਊਨ",
        "storageInfo" to "ਸਟੋਰੇਜ ਜਾਣਕਾਰੀ",
        "storage1" to "SQLite ਰੂਮ ਵਿੱਚ ਆਫਲਾਈਨ ਸੇਵ ਹੁੰਦਾ ਹੈ",
        "storage2" to "ਸੈਟਿੰਗਜ਼ ਫੋਨ ਵਿਚ ਬਣੀ ਰਹਿੰਦੀ ਹੈ",
        "storage3" to "ਫੋਟੋਆਂ ਡਿਵਾਈਸ ਵਿੱਚ ਸੁਰੱਖਿਅਤ ਹੁੰਦੀਆਂ ਹਨ",
        "storage4" to "100% ਆਫਲਾਈਨ — ਇੰਟਰਨੈਟ ਦੀ ਲੋੜ ਨਹੀਂ",
        "statusFresh" to "ਤਾਜ਼ਾ",
        "statusSoon" to "ਜਲਦ ਖ਼ਰਾਬ",
        "statusToday" to "ਅੱਜ ਹੀ ਮਿਆਦ ਖ਼ਤਮ",
        "statusExpired" to "ਮਿਆਦ ਖ਼ਤਮ",
        "expiresToday" to "ਅੱਜ ਹੀ ਖ਼ਰਾਬ ਹੋਵੇਗਾ!",
        "wasted" to "ਬਰਬਾਦ ਰੁਪਏ",
        "itemsExpired" to "ਮਿਆਦ ਪੁੱਗੀਆਂ ਆਈਟਮਾਂ",
        "thisMonth" to "ਇਸ ਮਹੀਨੇ",
        "monthlyWaste" to "ਮਾਸਿਕ ਨੁਕਸਾਨ",
        "wasteByCategory" to "ਕੈਟੇਗਰੀ ਮੁਤਾਬਕ ਬਰਬਾਦੀ",
        "expiredItems" to "ਖ਼ਰਾਬ ਹੋਈਆਂ ਚੀਜ਼ਾਂ",
        "googleDriveBackup" to "ਗੂਗਲ ਡਰਾਈਵ ਬੈਕਅੱਪ",
        "backupNow" to "ਡਰਾਈਵ ਤੇ ਸੇਵ ਕਰੋ",
        "restoreNow" to "ਡਰਾਈਵ ਤੋਂ ਰੀਸਟੋਰ ਕਰੋ",
        "driveBackupDesc" to "ਆਪਣਾ ਡੇਟਾ ਗੂਗਲ ਡਰਾਈਵ ਤੇ ਸੁਰੱਖਿਅਤ ਬੈਕਅੱਪ ਕਰੋ",
        "driveStatusNotConnected" to "ਗੂਗਲ ਖਾਤਾ ਲਿੰਕ ਨਹੀਂ ਹੈ",
        "driveStatusBackupSuccess" to "ਆਖਰੀ ਬੈਕਅੱਪ: ਹੁਣੇ",
        "shareBackup" to "ਲੋਕਲ ਬੈਕਅੱਪ ਫਾਈਲ ਸਾਂਝੀ ਕਰੋ",
        "importBackup" to "ਬੈਕਅੱਪ ਫਾਈਲ ਲਿਆਓ",
        "dangerZone" to "ਖਤਰਨਾਕ ਖੇਤਰ",
        "clearAllData" to "ਡੇਟਾਬੇਸ ਰੀਸੈਟ ਕਰੋ",
        "clearDataConfirm" to "ਕੀ ਤੁਸੀਂ ਯਕੀਨੀ ਤੌਰ ਤੇ ਸਾਰਾ ਡੇਟਾ ਮਿٹਾਉਣਾ ਚਾਹੁੰਦੇ ਹੋ?",
        "resetSuccess" to "ਐਪ ਰੀਸੈਟ ਸਫ਼ਲ!",
        "csvReportTitle" to "ਕੈਟੇਗਰੀ ਮੁਤਾਬਕ ਖ਼ਰਚੇ ਦਾ ਵੇਰਵਾ"
    ),
    "ur" to mapOf(
        "back" to "پیچھے",
        "addItem" to "آئٹم شامل کریں",
        "analytics" to "تجزیہ",
        "settings" to "سیٹنگز",
        "subtitle" to "کھانا ضائع ہونے سے بچائیں",
        "addFood" to "+ کھانا شامل کریں",
        "home" to "ہوم",
        "searchItems" to "آئٹم تلاش کریں...",
        "myInventory" to "میری انوینٹری",
        "items" to "آئٹمز",
        "totalItems" to "کل آئٹمز",
        "expiringSoon" to "جلد خراب ہونے والے",
        "expired" to "میعاد ختم",
        "alerts" to "الرٹس",
        "more" to "مزید",
        "bulkDelete" to "بلک ڈیلیٹ",
        "csv" to "CSV ایکسپورٹ",
        "all" to "تمام",
        "fresh" to "تازہ",
        "expiring" to "میعاد ختم ہونے والی",
        "noItems" to "کوئی آئٹم نہیں ملا",
        "addFirst" to "اپنا پہلا فوڈ آئٹم شامل کریں!",
        "noExpired" to "کوئی میعاد ختم آئٹم نہیں",
        "itemRemoved" to "آئٹم ہٹا دیا گیا",
        "expiredCleared" to "میعاد ختم آئٹمز صاف کر دیئے گئے!",
        "csvExported" to "CSV فائل ایکسپورٹ ہو گئی!",
        "deleteExpiredQ" to "کیا آپ تمام میعاد ختم آئٹمز ڈیلیٹ کرنا چاہتے ہیں؟",
        "cancel" to "منسوخ کریں",
        "delete" to "ڈیلیٹ",
        "saveItem" to "آئٹم محفوظ کریں",
        "photo" to "تصویر",
        "choosePhoto" to "تصویر منتخب کریں",
        "photoHint" to "لوکل ڈیوائس پر محفوظ ہے",
        "itemName" to "آئٹم کا نام",
        "itemNamePh" to "جیسے Amul Milk، Apple...",
        "category" to "کیٹیگری",
        "qtyUnit" to "مقدار اور یونٹ",
        "qtyPh" to "جیسے 500",
        "price" to "قیمت — اختیاری",
        "purchaseDate" to "خریداری کی تاریخ",
        "expiryDate" to "میعاد ختم ہونے کی تاریخ",
        "notes" to "نوٹس",
        "notesPh" to "جیسے فریج کے پیچھے رکھا ہے...",
        "nameRequired" to "آئٹم کا نام ضروری ہے",
        "expiryRequired" to "میعاد ختم ہونے کی تاریخ ضروری ہے",
        "appearance" to "لوک",
        "theme" to "تھیم",
        "darkMode" to "ڈارک موڈ",
        "lightMode" to "لائٹ موڈ",
        "language" to "زبان",
        "notifications" to "نوٹیفیکیشن",
        "enableNotifications" to "نوٹیفیکیشن فعال کریں",
        "dailyAt" to "روزانہ صبح 10:00 بجے",
        "alertTune" to "الرٹ ٹیون",
        "storageInfo" to "اسٹوریج معلومات",
        "storage1" to "آئٹمز روم ڈیٹا بیس میں آف لائن محفوظ ہوتے ہیں",
        "storage2" to "سیٹنگز محفوظ رہتی ہیں",
        "storage3" to "تصاویر موبائل میں محفوظ ہوتی ہیں",
        "storage4" to "100% آف لائن — انٹرنیٹ کی ضرورت نہیں",
        "statusFresh" to "تازہ",
        "statusSoon" to "جلد خراب",
        "statusToday" to "آج ہی میعاد ختم",
        "statusExpired" to "میعاد ختم",
        "expiresToday" to "آج ہی میعاد ختم ہوگی!",
        "wasted" to "ضائع",
        "itemsExpired" to "میعاد ختم آئٹمز",
        "thisMonth" to "اس مہینے",
        "monthlyWaste" to "ماہانہ نقصان",
        "wasteByCategory" to "کیٹیگری کے حساب سے نقصان",
        "expiredItems" to "میعاد ختم اشیاء",
        "googleDriveBackup" to "گوگل ڈرائیو بیک اپ",
        "backupNow" to "ڈرائیو پر بیک اپ لیں",
        "restoreNow" to "ڈرائیو سے ری سٹور کریں",
        "driveBackupDesc" to "اپنا ڈیٹا اپنے گوگل ڈرائیو پر محفوظ کریں",
        "driveStatusNotConnected" to "گوگل اکاؤنٹ منسلک نہیں ہے",
        "driveStatusBackupSuccess" to "آخری بیک اپ: ابھی لیا گیا",
        "shareBackup" to "لوکل بیک اپ فائل شیئر کریں",
        "importBackup" to "بیک اپ فائل امپورٹ کریں",
        "dangerZone" to "خطرناک زون",
        "clearAllData" to "ڈیٹا بیس ری سیٹ کریں",
        "clearDataConfirm" to "کیا آپ واقعی تمام آئٹمز ری سیٹ اور ختم کرنا چاہتے ہیں؟",
        "resetSuccess" to "ایپ ری سیٹ ہو گئی!",
        "csvReportTitle" to "کیٹیگری وائز اخراجات کا خلاصہ"
    )
)

val CAT_NAMES_LOCALIZED = mapOf(
    "en" to mapOf(
        "fruits_veg" to "Fruits & Vegetables",
        "dairy_eggs" to "Dairy & Eggs",
        "bakery_bread" to "Bakery & Bread",
        "meat_seafood" to "Meat & Seafood",
        "pantry_grains" to "Pantry & Grains",
        "beverages" to "Beverages",
        "others" to "Others"
    ),
    "hi" to mapOf(
        "fruits_veg" to "फल और सब्जियां",
        "dairy_eggs" to "डेयरी और अंडे",
        "bakery_bread" to "बेकरी और ब्रेड",
        "meat_seafood" to "मीट और सीफूड",
        "pantry_grains" to "पेंट्री और अनाज",
        "beverages" to "पेय पदार्थ",
        "others" to "अन्य"
    ),
    "bn" to mapOf(
        "fruits_veg" to "ফলমূল ও শাকসবজি",
        "dairy_eggs" to "দুগ্ধজাত ও ডিম",
        "bakery_bread" to "বেকারি ও পাউরুটি",
        "meat_seafood" to "মাংস ও সামুদ্রিক খাদ্য",
        "pantry_grains" to "প্যান্ট্রি ও খাদ্যশস্য",
        "beverages" to "পানীয় সামগ্রী",
        "others" to "অন্যান্য"
    ),
    "ta" to mapOf(
        "fruits_veg" to "பழங்கள் & காய்கறிகள்",
        "dairy_eggs" to "பால் & முட்டை",
        "bakery_bread" to "பேக்கரி & ரொட்டி",
        "meat_seafood" to "இறைச்சி & கடல் உணவு",
        "pantry_grains" to "தானியங்கள் & மளிகை",
        "beverages" to "பானங்கள்",
        "others" to "இதர பொருட்கள்"
    ),
    "te" to mapOf(
        "fruits_veg" to "పండ్లు & కూరగాయలు",
        "dairy_eggs" to "పాలు & గుడ్లు",
        "bakery_bread" to "బేకరీ & బ్రెడ్",
        "meat_seafood" to "మాంసం & సీఫుడ్",
        "pantry_grains" to "ధాన్యాలు & గింజలు",
        "beverages" to "పానీయాలు",
        "others" to "ఇతరాలు"
    ),
    "mr" to mapOf(
        "fruits_veg" to "फळे आणि भाज्या",
        "dairy_eggs" to "दूध आणि अंडी",
        "bakery_bread" to "बेकरी आणि ब्रेड",
        "meat_seafood" to "मटण आणि सीफूड",
        "pantry_grains" to "धान्य आणि कडधान्ये",
        "beverages" to "पेये",
        "others" to "इतर"
    ),
    "gu" to mapOf(
        "fruits_veg" to "ફળો અને શાકભાજી",
        "dairy_eggs" to "ડેરી અને ઇંડા",
        "bakery_bread" to "બેકરી અને બ્રેડ",
        "meat_seafood" to "મીટ અને સીફૂડ",
        "pantry_grains" to "અનાજ અને કઠોળ",
        "beverages" to "પીણાં",
        "others" to "અન્ય"
    ),
    "kn" to mapOf(
        "fruits_veg" to "ಹಣ್ಣುಗಳು ಮತ್ತು ತರಕಾರಿಗಳು",
        "dairy_eggs" to "ಡೈರಿ ಮತ್ತು ಮೊಟ್ಟೆಗಳು",
        "bakery_bread" to "ಬೇಕರಿ ಮತ್ತು ಬ್ರೆಡ್",
        "meat_seafood" to "ಮಾಂಸ ಮತ್ತು ಸೀಫುಡ್",
        "pantry_grains" to "ಧಾನ್ಯಗಳು ಮತ್ತು ಬೇಳೆಗಳು",
        "beverages" to "ಪಾನೀಯಗಳು",
        "others" to "ಇತರೆ"
    ),
    "ml" to mapOf(
        "fruits_veg" to "പഴങ്ങളും പച്ചക്കറികളും",
        "dairy_eggs" to "പാൽ ഉൽപ്പന്നങ്ങളും മുട്ടയും",
        "bakery_bread" to "ബേക്കറിയും ബ്രെഡും",
        "meat_seafood" to "ഇറച്ചിയും മീനും",
        "pantry_grains" to "ധാന്യങ്ങളും അവശ്യവസ്തുക്കളും",
        "beverages" to "പാനീയങ്ങൾ",
        "others" to "മറ്റുള്ളവ"
    ),
    "pa" to mapOf(
        "fruits_veg" to "ਫਲ ਅਤੇ ਸਬਜ਼ੀਆਂ",
        "dairy_eggs" to "ਡੇਅਰੀ ਅਤੇ ਆਂਡੇ",
        "bakery_bread" to "ਬੇਕਰੀ ਅਤੇ ਬਰੈੱਡ",
        "meat_seafood" to "ਮੀਟ ਅਤੇ ਸੀਫੂਡ",
        "pantry_grains" to "ਅਨਾਜ ਅਤੇ ਕਣਕ",
        "beverages" to "ਪੀਣ ਵਾਲੇ ਪਦਾਰਥ",
        "others" to "ਹੋਰ"
    ),
    "ur" to mapOf(
        "fruits_veg" to "پھل اور سبزیاں",
        "dairy_eggs" to "ڈیری اور انڈے",
        "bakery_bread" to "بیکری اور روٹی",
        "meat_seafood" to "گوشت اور سی فوڈ",
        "pantry_grains" to "پینٹری اور اناج",
        "beverages" to "مشروبات",
        "others" to "دیگر"
    )
)

fun translateExt(key: String, lang: String): String {
    return I18N_LOCALIZED[lang]?.get(key)
        ?: I18N_LOCALIZED["en"]?.get(key)
        ?: key
}

fun getCategoryLabelExt(cat: String, lang: String): String {
    return CAT_NAMES_LOCALIZED[lang]?.get(cat)
        ?: CAT_NAMES_LOCALIZED["en"]?.get(cat)
        ?: cat
}

object OnboardingGuideI18n {
    val languages = mapOf(
        "en" to mapOf(
            "welcome_title" to "Welcome to FreshTrack",
            "welcome_subtitle" to "Premium Offline Grocery Assistant",
            "welcome_desc" to "Keep food fresh! FreshTrack helps you track and manage your grocery inventory, alerts you before expiry, and saves you money.",
            "welcome_next" to "Next Step ➔",
            "privacy_title" to "Privacy & Safe Eating",
            "privacy_desc" to "FreshTrack operates 100% offline. No logins, tracking SDKs or secret servers. Backups are stored strictly under Android's private pipeline.",
            "privacy_terms" to "I accept the Privacy Policy & Offline Terms.",
            "privacy_safe" to "I will inspect actual food labels, smell, and state before eating.",
            "guide_title" to "App Quick Guide",
            "guide_step1_title" to "1. Welcome & Grocery Setup",
            "guide_step1_desc" to "Track shelf life easily to save money. We provide zero-waste analytics of expiries and food spent, completely offline.",
            "guide_step2_title" to "2. Capture Items & Smart Category",
            "guide_step2_desc" to "Tap '+' and key in items. Categories automatically set units. Tap Camera to capture a live photo of your receipt or product!",
            "guide_step3_title" to "3. Local Alerts & Backups",
            "guide_step3_desc" to "Receive offline notification reminders 2 days prior to expiration. Setup manual JSON backup files or Android Auto-Backup!",
            "btn_agree" to "Agree & Continue",
            "btn_start" to "Start Using FreshTrack",
            "btn_back" to "Back"
        ),
        "hi" to mapOf(
            "welcome_title" to "FreshTrack में स्वागत है",
            "welcome_subtitle" to "प्रीमियम ऑफलाइन ग्रोसरी सहायक",
            "welcome_desc" to "भोजन को ताजा रखें! फ्रेशट्रैक रसोई सूची प्रबंधित करने, शेल्फ लाइफ ट्रैक करने और पैसे बचाने में मदद करता है।",
            "welcome_next" to "अगला चरण ➔",
            "privacy_title" to "गोपनीयता और खाद्य सुरक्षा",
            "privacy_desc" to "फ्रेशट्रैक 100% ऑफलाइन कार्य करता है। हम कभी क्लाउड पर डेटा नहीं भेजते। बैकअप आपकी निजी डिवाइस में रहते हैं।",
            "privacy_terms" to "मैं गोपनीयता नीति एवं नियम स्वीकार करता हूँ।",
            "privacy_safe" to "मैं भोजन के वास्तविक लेबल, सुगंध एवं स्थिति की जांच स्वयं करूँगा।",
            "guide_title" to "त्वरित मार्गदर्शिका",
            "guide_step1_title" to "1. स्वागत और ग्रोसरी सेटअप",
            "guide_step1_desc" to "पैसे बचाने के लिए शेल्फ लाइफ ट्रैक करें। ऑफलाइन जीरो-वेस्ट एनालिटिक्स से खर्च प्रबंधित करें।",
            "guide_step2_title" to "2. आइटम और स्मार्ट कैटेगरी",
            "guide_step2_desc" to "प्लस (+) दबाएं, नाम भरें। कैटेगरी से मात्रा इकाई स्वतः तय होगी। गैलरी से चुनें या लाइव फोटो लें।",
            "guide_step3_title" to "3. अलर्ट और सुरक्षित बैकअप",
            "guide_step3_desc" to "एक्सपायरी से 2 दिन पहले ऑफलाइन नोटिफिकेशन पाएं। गूगल ड्राइव या मैनुअल JSON से रिस्टोर करें।",
            "btn_agree" to "स्वीकार और जारी रखें",
            "btn_start" to "फ्रेशट्रैक का उपयोग शुरू करें",
            "btn_back" to "वापस"
        ),
        "bn" to mapOf(
            "welcome_title" to "ফ্রেশট্যাকে স্বাগতম",
            "welcome_subtitle" to "প্রিমিয়াম অফলাইন গ্রোসারি সহকারী",
            "welcome_desc" to "খাবার তাজা রাখুন! এটি আপনাকে গ্রোসারি ট্র্যাক করতে, মেয়াদের আগে সতর্ক করতে এবং অপচয় ঠেকাতে সাহায্য করে।",
            "welcome_next" to "পরের ধাপ ➔",
            "privacy_title" to "গোপনীয়তা ও খাদ্য নিরাপত্তা",
            "privacy_desc" to "ফ্রেশট্যাক ১০০% অফলাইন। কোনো ক্লাউড সার্ভার নেই। ব্যাকআপ নিরাপদে ডিভাইসে সংরক্ষিত থাকে।",
            "privacy_terms" to "আমি গোপনীয়তা নীতি ও শর্তাবলী স্বীকার করছি।",
            "privacy_safe" to "আমি খাওয়ার আগে খাবারের গন্ধ, প্যাকেজিং ও তাজা অবস্থা পরীক্ষা করব।",
            "guide_title" to "অ্যাপ নির্দেশিকা",
            "guide_step1_title" to "১. স্বাগত ও গ্রোসারি সেটআপ",
            "guide_step1_desc" to "সহজে খাবারের মেয়াদ ট্র্যাক করে খরচ কমান। খাবার অপচয় ঠেকাতে তাजा থাকার অফলাইন পরিসংখ্যান দেখুন।",
            "guide_step2_title" to "২. আইটেম ও স্মার্ট ক্যাটাগরি",
            "guide_step2_desc" to "প্লাস আইকন টিপুন এবং নতুন আইটেম যুক্ত করুন। ফটো নিতে ক্যামেরা বা গ্যালারি ব্যবহার করুন।",
            "guide_step3_title" to "৩. স্থানীয় সতর্কতা ও ব্যাকআপ",
            "guide_step3_desc" to "মেয়াদ শেষের ২ দিন আগে রিমাইন্ডার পাবেন। আপনার গুগল ড্রাইভ ব্যাকআপ বা এক্সপোর্ট ব্যবহার করুন।",
            "btn_agree" to "সম্মত হোন ও এগিয়ে যান",
            "btn_start" to "ফ্রেশট্যাক ব্যবহার শুরু করুন",
            "btn_back" to "পিছনে"
        ),
        "ta" to mapOf(
            "welcome_title" to "பிரெஷ்டிராக்கிற்கு வரவேற்கிறோம்",
            "welcome_subtitle" to "பல்நோக்கு ஆஃப்লাইন மளிகை உதவியாளர்",
            "welcome_desc" to "உணவை புதியதாக வைத்திருங்கள்! மளிகை பட்டியலை நிர்வகிக்கவும், வீணாவதைத் தவிர்க்கவும் இது உதவுகிறது.",
            "welcome_next" to "அடுத்த படி ➔",
            "privacy_title" to "தனியுரிமை மற்றும் உணவுப் பாதுகாப்பு",
            "privacy_desc" to "இந்த செயலி 100% ஆஃப்லைனில் செயல்படுகிறது. சேமிக்கப்பட்ட காப்புப்பிரதிகள் முற்றிலும் உங்களுடையவை.",
            "privacy_terms" to "தனியுரிமை கொள்கை மற்றும் ஒழுங்குமுறைகளை ஏற்கிறேன்.",
            "privacy_safe" to "உணவை உட்கொள்ளும் முன் அதன் சுவை, மணம் மற்றும் தரத்தை நானே சரிபார்ப்பேன்.",
            "guide_title" to "விரைவு உதவிக்குறிப்பு",
            "guide_step1_title" to "1. முகப்பு & சரக்கு அமைப்பு",
            "guide_step1_desc" to "பொருட்களை வீணாக்காமல் சேமிக்க காலாவதி தேதியை சேர்க்கவும். முழுமையான ஆஃப்லைன் பகுப்பாய்வு.",
            "guide_step2_title" to "2. பொருட்கள் & நேரடி புகைப்படம்",
            "guide_step2_desc" to "மளிகை பொருட்களைச் சேர்க்க பிளஸ் தாவவும். கேமரா அம்சத்துடன் நேரடி புகைப்படங்களை எடுக்கலாம்.",
            "guide_step3_title" to "3. உள்ளூர் விழிப்பூட்டல்கள் & காப்புப்பிரதி",
            "guide_step3_desc" to "பொருட்கள் மெதுவாக கெட்டுப்போவதை தடுக்க 2 நாட்களுக்கு முன் அலர்ட் வரும். கோப்புகளை பேக்கப் செய்யலாம்.",
            "btn_agree" to "ஏற்றுக்கொண்டு தொடரவும்",
            "btn_start" to "பயன்படுத்த தொடங்குங்கள்",
            "btn_back" to "முந்தைய"
        ),
        "te" to mapOf(
            "welcome_title" to "ఫ్రెష్‌ట్రాక్కు స్వాగతం",
            "welcome_subtitle" to "ప్రీమియం ఆఫ్లైన్ కిరాణా సహాయకుడు",
            "welcome_desc" to "ఆహారాన్ని వృథా కాకుండా తాజాగా ఉంచండి. గడువు ముగిసే కంటే ముందే మిమ్మల్ని హెచ్చరిస్తుంది.",
            "welcome_next" to "తదుపరి దశ ➔",
            "privacy_title" to "గోప్యత మరియు ఆహార భద్రత",
            "privacy_desc" to "ఫ్రెష్‌ట్రాక్ 100% ఆఫ్‌లైన్‌లో పనిచేస్తుంది. ఖాతాల అవసరం లేదు. మీ డేటా మీ మొబైల్ లోనే సురક્ષితంగా ఉంటుంది.",
            "privacy_terms" to "నేను గోప్యతా విధానం మరియు నిబంధనలను అంగీకరిస్తున్నాను.",
            "privacy_safe" to "నేను ఆహారాన్ని తినేముందు స్వయంగా దాని నాణ్యత, సువాసనను పరిశీలిస్తాను.",
            "guide_title" to "యాప్ గైడ్",
            "guide_step1_title" to "1. స్వాగతం & ఇన్వెنتరీ హోమ్",
            "guide_step1_desc" to "ఇన్వెنتరీ సులభంగా నిర్వహించండి. ఆఫ్‌లైన్‌లో వృథా ఖర్చును విశ్లేషించండి.",
            "guide_step2_title" to "2. వస్తువులు & స్మార్ట్ కేటగిరీ",
            "guide_step2_desc" to "ప్లస్ క్లిక్ చేసి ఐటమ్స్ జోడించండి. కెమెరా తో లైవ్ ఫోటోలు క్యాప్చర్ చేయవచ్చు.",
            "guide_step3_title" to "3. స్థానిక అలర్ట్‌లు & బ్యాకప్",
            "guide_step3_desc" to "గడువు కంటే 2 రోజుల ముందే హెచ్చరిక అలర్ట్ లభిస్తుంది. సురಕ್ಷిత బ్యాకప్ చేసుకోవచ్చు.",
            "btn_agree" to "అంగీకరించి కొనసాగించు",
            "btn_start" to "ప్రారంభించండి",
            "btn_back" to "వెనుకకు"
        ),
        "mr" to mapOf(
            "welcome_title" to "फ्रेशट्रॅक मध्ये स्वागत आहे",
            "welcome_subtitle" to "प्रीमियम ऑफलाइन ग्रोसरी मदतनीस",
            "welcome_desc" to "अन्न वाया जाण्यापासून वाचवा! फ्रेशट्रॅक तुम्हाला अन्नाचा खर्च आणि एक्सपायरी व्यवस्थापित करण्यास मदत करतो.",
            "welcome_next" to "पुढील पायरी ➔",
            "privacy_title" to "गोपनीयता आणि सुरक्षितता",
            "privacy_desc" to "फ्रेशट्रॅक 100% ऑफलाइन आहे. आम्ही डेटा सर्वरवर पाठवत नाही. सर्व बॅकअप सुरक्षित ऑफलाइन राहतात.",
            "privacy_terms" to "मी गोपनीयता धोरण आणि नियम मान्य करतो.",
            "privacy_safe" to "खाण्यापूर्वी अन्नाची एक्सपायरी आणि ताजेपणा स्वतः तपासेन.",
            "guide_title" to "मार्गदर्शिका",
            "guide_step1_title" to "१. स्वागत आणि सेटअप",
            "guide_step1_desc" to "पैसे वाचवण्यासाठी अन्न ताजे ठेवा. ऑफलाइन आलेखांद्वारे अन्नाची नासाडी व्यवस्थापित करा.",
            "guide_step2_title" to "२. वस्तू आणि कॅमेरा फोटो",
            "guide_step2_desc" to "प्लस (+) टॅप करून वस्तू भरा. कॅमेऱ्याने लाईव्ह फोटो आणि युनिट निवडा.",
            "guide_step3_title" to "३. रिमाइंडर्स आणि सुरक्षित बॅकअप",
            "guide_step3_desc" to "पदार्थ खराब होण्यापूर्वी रोज ऑफलाइन नोटिफिकेशन स्मरणपत्रे मिळवा. गुगल ड्राइव्ह बॅकअप वापरा.",
            "btn_agree" to "मान्य करा आणि पुढे जा",
            "btn_start" to "फ्रेशट्रॅक वापरणे सुरू करा",
            "btn_back" to "मागे"
        ),
        "gu" to mapOf(
            "welcome_title" to "ફ્રેશટ્રેકમાં સ્વાગત છે",
            "welcome_subtitle" to "પ્રીમિયમ ઓફલાઇન કરિયાણા વ્યવસ્થાપક",
            "welcome_desc" to "ખોરાકનો બગાડ અટકાવો. ફ્રેશટ્રેક તમને મુદત વીતતા પહેલા જાગૃત કરશે જેથી પૈસા બચશે.",
            "welcome_next" to "આગળનું પગલું ➔",
            "privacy_title" to "પ્રાઇવસી અને ફૂડ સેફ્ટી",
            "privacy_desc" to "એપ સંપૂર્ણ ઓફલાઇન ચાલે છે. કોઈ સર્વર નથી. બધો જ ડેટા તમારા ઉપકરણમાં ટ્રેક થાય છે.",
            "privacy_terms" to "હું પ્રાઇવસી પોલિસી અને નિયમો સ્વીકારું છું.",
            "privacy_safe" to "ખોરાક ખાતા પહેલા એની સુગંધ, પેકિંગ અને શુદ્ધતાની જાતે ખાતરી કરીશ.",
            "guide_title" to "ઝડપી માર્ગદર્શિકા",
            "guide_step1_title" to "૧. સ્વાગત અને સેટઅપ",
            "guide_step1_desc" to "બગાડ ઓછો કરવા ગ્રોસરી યાદી બનાવો. ઓફલાઇન એનાલિટિક્સ ફીચર.",
            "guide_step2_title" to "૨. વસ્તુઓ અને કેમેરા ફોટો",
            "guide_step2_desc" to "પ્લસ બટન દબાવો, નામ લખો. કેટેગરી સેટ કરી કેમેરા વડે નવો ફોટો પણ ઉમેરી શકો છો.",
            "guide_step3_title" to "૩. નોટિફિકેશન અને બેકઅપ",
            "guide_step3_desc" to "એક્સપાયરીના ૨ દિવસ પહેલા યાદ અપાવશે. કલાઉડ અથવા મેન્યુઅલ બેકઅપ લઇ લો.",
            "btn_agree" to "સ્વીકારો અને આગળ વધો",
            "btn_start" to "શરૂ કરો",
            "btn_back" to "પાછા"
        ),
        "kn" to mapOf(
            "welcome_title" to "ಫ್ರೆಶ್‌ಟ್ರಾಕ್‌ಗೆ ಸುಸ್ವಾಗತ",
            "welcome_subtitle" to "ಆಫ್‌ಲೈನ್ ಅತ್ಯುತ್ತಮ ಗ್ರೋಸರಿ ಸಹಾಯಕ",
            "welcome_desc" to "ಆಹಾರವನ್ನು ವ್ಯರ್ಥವಾಗದಂತೆ ತಾಜಾವಾಗಿರಿಸಿ! ಇದು ಗಡುವು ಮುಗಿಯುವ ಮುನ್ನವೇ ಎಚ್ಚರಿಕೆ ರವಾನಿಸುತ್ತದೆ.",
            "welcome_next" to "ಮುಂದಿನ ಹಂತ ➔",
            "privacy_title" to "ಗೌಪ್ಯತೆ ಮತ್ತು ಆಹಾರ ಭದ್ರತೆ",
            "privacy_desc" to "ಆಪ್ ಸಂಪೂರ್ಣ ಆಫ್‌ಲೈನ್ ಆಗಿದೆ. ಬ್ಯಾಕಪ್ ಸಂಪೂರ್ಣವಾಗಿ ನಿಮ್ಮ ಮೊಬೈಲ್ ನಲ್ಲೇ ಸುರಕ್ಷಿತವಾಗಿರುತ್ತದೆ.",
            "privacy_terms" to "ನಾನು ಗೌಪ್ಯತೆ ನೀತಿ ಮತ್ತು ನಿಯಮಗಳನ್ನು ಒಪ್ಪುತ್ತೇನೆ.",
            "privacy_safe" to " ತಿನ್ನುವ ಮುನ್ನ ಆಹಾರದ ವಾಸನೆ, ಲೇಬಲ್ ಹಾಗು ಅದರ ಸ್ಥಿತಿಯನ್ನು ಪರಿಶೀಲಿಸುತ್ತೇನೆ.",
            "guide_title" to "ತ್ವರಿತ ಗೈಡ್",
            "guide_step1_title" to "1. ಸುಸ್ವಾಗತ ಮತ್ತು ಗ್ರೋಸರಿ ಲಾಗ್",
            "guide_step1_desc" to "ನಿಮ್ಮ ದಿನಸಿ ನಿರ್ವಹಣೆ এখন ಸರಳ. ಆಫ್‌ಲೈನ್‌ನಲ್ಲಿ ಉಳಿತಾಯ ವಿಶ್ಲೇಷಣೆ.",
            "guide_step2_title" to "2. ಸಾಮಗ್ರಿ ಮತ್ತು ಲೈವ್ ಕ್ಯಾಮೆರಾ",
            "guide_step2_desc" to "ಪ್ಲಸ್ ಕ್ಲಿಕ್ ಮಾಡಿ ಹೊಸ ಸಾಮಗ్రి ಸೇರಿಸಿ ಹಾಗು ಲೈವ್ ಫೋಟೋಗಳನ್ನು ಒದಗಿಸಬಹುದು.",
            "guide_step3_title" to "3. ಆಫ್‌ಲೈನ್ ಅಲರ್ಟ್‌ಗಳು & ಬ್ಯಾಕಪ್",
            "guide_step3_desc" to "ಗಡುವು ಮುಗಿಯುವ 2 ದಿನ ಮುಂಚಿತವಾಗಿ ಎಚ್ಚರಿಕೆ ಅಲರ್ಟ್ ಪಡೆಯಿರಿ. ಬ್ಯಾಕಪ್ ಸರಳವಾಗಿ ಇಂಪೋರ್ಟ್ ಮಾಡಿ.",
            "btn_agree" to "ಒಪ್ಪಿ ಮುಂದಕ್ಕೆ ಹೋಗి",
            "btn_start" to "ಫ್ರೆಶ್‌ಟ್ರಾಕ್ ಬಳಸಿ",
            "btn_back" to "ಹಿಂದಕ್ಕೆ"
        ),
        "ml" to mapOf(
            "welcome_title" to "ഫ്രെഷ്‌ട്രാക്കിലേക്ക് സ്വാഗതം",
            "welcome_subtitle" to "പ്രീമിയം ഓഫ്‌ലൈൻ ഗ്രോസറി അസിസ്റ്റൻ്റ്",
            "welcome_desc" to "ഭക്ഷണം പുതുമയോടെ സൂക്ഷിക്കുക! എക്സ്പെയറിക്ക് മുൻപ് അലേർട്ട് നൽകി പണം ലാഭിക്കാൻ സഹായിക്കുന്നു.",
            "welcome_next" to "അടുത്ത ഘട്ടം ➔",
            "privacy_title" to "സ്വകാര്യതയും സുരക്ഷിതത്വവും",
            "privacy_desc" to "ഫ്രെഷ്‌ട്രാക്ക് 100% ഓഫ്‌ലൈനാണ്. നിങ്ങളുടെ വിവരങ്ങൾ ഫോണിൽ തന്നെ സുരക്ഷിതമായിരിക്കും.",
            "privacy_terms" to "ഞാൻ നിബന്ധനകളും സ്വകാര്യതാ നയവും അംഗീകരിക്കുന്നു.",
            "privacy_safe" to "കഴിക്കുന്നതിന് മുൻപ് ഭക്ഷണത്തിൻ്റെ മണം, ലേബൽ എന്നിവ ഞാൻ പരിശോധിച്ചുകൊള്ളാം.",
            "guide_title" to "ദ്രുത മാർഗ്ഗനിർദ്ദേശം",
            "guide_step1_title" to "1. സ്വാഗതം & ഗ്രോസറി സജ്ജീകരണം",
            "guide_step1_desc" to "അനായാസം എക്സ്പെയറി ട്രാക്ക് ചെയ്യുക. പണം ലാഭിക്കാൻ ഓഫ്‌ലൈൻ അനലിറ്റിക്സ് സഹായിക്കുന്നു.",
            "guide_step2_title" to "2. ഉൽപ്പന്നങ്ങളും ക്യാമറ ചിത്രങ്ങളും",
            "guide_step2_desc" to "പ്ലസ് ഉപയോഗിച്ച് പുതിയ ഉൽപ്പന്നങ്ങൾ ചേർക്കാം. ക്യാമറ വഴി ഫോട്ടോയും എടുക്കാം.",
            "guide_step3_title" to "3. അലേർട്ടുകൾ & സുരക്ഷിത ബാക്കപ്പ്",
            "guide_step3_desc" to "എക്സ്പെയറിക്ക് 2 ദിവസം മുൻപ് ദിവസേന ഓർമ്മപ്പെടുത്തലുകൾ നേടാം. ഗൂഗിൾ ഡ്രൈവിലേക്ക് ബാക്കപ്പ് ചെയ്യുക.",
            "btn_agree" to "അംഗീകരിച്ച് മുന്നോട്ട് പോകുക",
            "btn_start" to "ഉപയോഗിച്ച് തുടങ്ങുക",
            "btn_back" to "പിന്നിലേക്ക്"
        ),
        "pa" to mapOf(
            "welcome_title" to "ਫਰੈਸ਼ਟ੍ਰੈਕ ਵਿੱਚ ਜੀ ਆਇਆਂ ਨੂੰ",
            "welcome_subtitle" to "ਪ੍ਰੀਮੀਅਮ ਆਫ਼ਲਾਈਨ ਰਸੋਈ ਸਹਾਇਕ",
            "welcome_desc" to "ਭੋਜਨ ਤਾਜ਼ਾ ਰੱਖੋ! ਫਰੈਸ਼ਟ੍ਰੈਕ ਤੁਹਾਨੂੰ ਖਰਾਬ ਹੋਣ ਤੋਂ ਪਹਿਲਾਂ ਸੁਚੇਤ ਕਰਕੇ ਤੁਹਾਡੇ ਪੈਸੇ ਬਚਾਉਂਦਾ ਹੈ।",
            "welcome_next" to "ਅਗਲਾ ਕਦਮ ➔",
            "privacy_title" to "ਪ੍ਰਾਈਵੇਸੀ ਅਤੇ ਫੂਡ ਸੇਫਟੀ",
            "privacy_desc" to "ਇਹ ਐਪ 100% ਆਫ਼ਲਾਈਨ ਕੰਮ ਕਰਦੀ ਹੈ। ਤੁਹਾਡਾ ਸਾਰਾ ਡਾਟਾ ਤੁਹਾਡੇ ਫੋਨ ਵਿੱਚ ਹੀ ਸੁਰੱਖਿਅਤ ਰਹਿੰਦਾ ਹੈ।",
            "privacy_terms" to "ਮੈਂ ਪ੍ਰਾਈਵੇਸੀ ਪਾਲਿਸੀ ਅਤੇ ਸ਼ਰਤਾਂ ਨੂੰ ਸਵੀਕਾਰ ਕਰਦਾ ਹਾਂ।",
            "privacy_safe" to "ਮੈਂ ਖਾਣ ਤੋਂ ਪਹਿਲਾਂ ਭੋਜਨ ਦੀ ਮਹਿਕ, ਲੇਬਲ ਅਤੇ ਸਥਿਤੀ ਦੀ ਜਾਂਚ ਆਪ ਕਰਾਂਗਾ।",
            "guide_title" to "ਤੁਰੰਤ ਗਾਈਡ",
            "guide_step1_title" to "1. ਜੀ ਆਇਆਂ ਨੂੰ ਅਤੇ ਸੈਟਅਪ",
            "guide_step1_desc" to "ਬਰਬਾਦੀ ਰੋਕਣ ਲਈ ਐਕਸਪਾਇਰੀ ਟ੍ਰੈਕ ਕਰੋ। ਆਫ਼ਲਾਈਨ ਐਨਾਲਿਟਿਕਸ ਦੀ ਵਰਤੋਂ ਕਰੋ।",
            "guide_step2_title" to "2. ਚੀਜ਼ਾਂ ਅਤੇ ਫੋਟੋਆਂ ਸ਼ਾਮਲ ਕਰੋ",
            "guide_step2_desc" to "ਪਲੱਸ ਬਟਨ ਦਬਾ ਕੇ ਨਵੇਂ ਆਈਟਮ ਜੋੜੋ। ਤੁਸੀਂ ਲਾਈਵ ਕੈਮਰਾ ਫੋਟো ਵੀ ਖਿੱਚ ਸਕਦੇ ਹੋ।",
            "guide_step3_title" to "3. ਰੀਮਾਈਂਡਰ ਅਤੇ ਬੈਕਅੱਪ",
            "guide_step3_desc" to "ਆਈਟਮ ਆਫ਼ਲਾਈਨ ਐਕਸਪਾਇਰੀ ਤੋਂ 2 ਦਿਨ ਪਹਿਲਾਂ ਸੁਚੇਤ ਕਰੇਗੀ। ਗੂਗਲ ਡਰਾਈਵ ਤੇ ਬੈਕਅੱਪ ਸੁਰੱਖਿਅਤ ਕਰੋ।",
            "btn_agree" to "ਸਹਿਮਤ ਹੋਵੋ ਅਤੇ ਅੱਗੇ ਵਧੋ",
            "btn_start" to "ਵਰਤੋਂ ਸ਼ੁਰੂ ਕਰੋ",
            "btn_back" to "ਪਿੱਛੇ"
        ),
        "ur" to mapOf(
            "welcome_title" to "FreshTrack میں خوش آمدید",
            "welcome_subtitle" to "پریمیم آف لائن گروسری اسسٹنٹ",
            "welcome_desc" to "کھانے کو تازہ رکھیں! فریش ٹریک آپ کے کچن کی انوینٹری کا انتظام کرنے، شیلف لائف کو ٹریک کرنے اور پیسے بچانے میں مدد کرتا ہے۔",
            "welcome_next" to "اگلا مرحلہ ➔",
            "privacy_title" to "رازداری اور فوڈ سیفٹی",
            "privacy_desc" to "فریش ٹریک 100% آف لائن کام کرتا ہے۔ ہم کبھی بھی کلاؤڈ پر ڈیٹا نہیں بھیجتے۔ تمام بیک اپ آپ کے اپنے ڈیوائس پر محفوظ رہتے ہیں۔",
            "privacy_terms" to "میں رازداری کی پالیسی اور شرائط کو قبول کرتا ہوں۔",
            "privacy_safe" to "میں کھانے سے پہلے کھانے کے اصل لیبل، بو اور حالت کی خود جانچ کروں گا۔",
            "guide_title" to "فوری رہنما کتابچہ",
            "guide_step1_title" to "1. خوش آمدید اور گروسری سیٹ اپ",
            "guide_step1_desc" to "پیسے بچانے کے لیے کھانے کی شیلف لائف ٹریک کریں۔ آف لائن زیرو ویسٹ اینالیٹکس سے کچن کے اخراجات کا انتظام کریں۔",
            "guide_step2_title" to "2. آئٹمز اور اسمارٹ کیٹیگری",
            "guide_step2_desc" to "پلس (+) بٹن دبائیں اور آئٹم کا نام درج کریں۔ کیٹیگری سے یونٹ خود بخود طے ہو جائے گا۔ گیلری سے منتخب کریں یا فوٹو لیں۔",
            "guide_step3_title" to "3. الرٹس اور محفوظ بیک اپ",
            "guide_step3_desc" to "میعاد ختم ہونے سے 2 دن پہلے روزانہ آف لائن نوٹیفیکیشن حاصل کریں۔ گوگل ڈرائیو یا مینوئل JSON سے ڈیٹا بیک اپ کریں۔",
            "btn_agree" to "تسلیم کریں اور آگے بڑھیں",
            "btn_start" to "فریش ٹریک کا استعمال شروع کریں",
            "btn_back" to "پیچھے"
        )
    )

    fun get(key: String, lang: String): String {
        return languages[lang]?.get(key)
            ?: languages["en"]?.get(key)
            ?: key
    }
}
